#!/bin/csh
#$ -M mdoellma@nd.edu
#$ -m abe
#$ -r y
#$ -pe smp 8
#$ -q long
#$ -N BeautifySpa
#$ -cwd
#$ -v DISPLAY

module load bio
#Filter out non-Mendax indivs
#vcftools --vcf Sparklef.map.merged.q30.GATK.UG.vcf --keep allRmend.txt --recode --recode-INFO-all --out Sparklef.keep

#Get basic SNP information
#vcftools --vcf Sparklef.keep.recode.vcf --out Sparklef.keep.recode --missing-indv
#vcftools --vcf Sparklef.keep.recode.vcf --out Sparklef.keep.recode --missing-site

#vcftools --vcf Sparklef.keep.recode.vcf --max-missing 0.5 --mac 3 --minQ 30 --recode --recode-INFO-all --out Sparklef.keep.50.3.30
#vcftools --vcf Sparklef.keep.50.3.30.recode.vcf --out Sparklef.keep.50.3.30 --missing-indv
#vcftools --vcf Sparklef.keep.50.3.30.recode.vcf --remove-indels --min-alleles 2 --max-alleles 2 --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi
#vcftools --vcf Sparklef.keep.50.3.30.bi.recode.vcf --out Sparklef.keep.50.3.30.bi --missing-indv
#vcftools --vcf Sparklef.keep.50.3.30.bi.recode.vcf --out  Sparklef.keep.50.3.30.bi --depth

#vcftools --vcf Sparklef.keep.50.3.30.bi.recode.vcf --keep coverageIndiv75.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf --out Sparklef.keep.50.3.30.bi.75 --depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf --out Sparklef.keep.50.3.30.bi.75 --site-depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf --out Sparklef.keep.50.3.30.bi.75 --site-mean-depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf --out Sparklef.keep.50.3.30.bi.75 --missing-site
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf --out Sparklef.keep.50.3.30.bi.75 --missing-indv
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep blue.ns.txt --missing-site --out ns
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep blue.nj.txt --missing-site --out nj
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep blue.bga.txt --missing-site --out bga
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep blue.lbl.txt --missing-site --out lbl
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep blue.jp.txt --missing-site --out jp
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep odb.txt --missing-site --out odb
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep osb.txt --missing-site --out osb
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep blue.aiken.txt --missing-site --out aiken
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep db.al.txt --missing-site --out aldb
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep db.ar.txt --missing-site --out ardb
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep db.sc.txt --missing-site --out scdb
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep sb.al.txt --missing-site --out alsb
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep sb.ar.txt --missing-site --out arsb
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.recode.vcf  --keep sb.sc.txt --missing-site --out scsb

#module load perl
#perl FilterScatteredGatkVcfs.pl 0.05 0 0.05 21
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --out Sparklef.keep.50.3.30.bi.75.filtered --site-mean-depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --out Sparklef.keep.50.3.30.bi.75.filtered --site-depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --out Sparklef.keep.50.3.30.bi.75.filtered --missing-site 
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --out Sparklef.keep.50.3.30.bi.75.filtered --depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --out Sparklef.keep.50.3.30.bi.75.filtered --missing-indv 

#HWE in fenn
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --keep blue.fenn.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.fenn

#GenomeAnalysisTK \
#-R MendaxGenome/MendaxGenome.fasta \
#-T VariantAnnotator \
#--variant Sparklef.keep.50.3.30.bi.75.filtered.fenn.recode.vcf \
#-o Sparklef.keep.50.3.30.bi.75.filtered.fenn.HWE.vcf \
#-A HardyWeinberg

#perl ExtractHWE.pl Sparklef.keep.50.3.30.bi.75.filtered.fenn.HWE.vcf Sparklef.keep.50.3.30.bi.75.filtered.fenn.HWE.pass.txt

#HWE in aiken
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --keep blue.aiken.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.aiken

#GenomeAnalysisTK \
#-R MendaxGenome/MendaxGenome.fasta \
#-T VariantAnnotator \
#--variant Sparklef.keep.50.3.30.bi.75.filtered.aiken.recode.vcf \
#-o Sparklef.keep.50.3.30.bi.75.filtered.aiken.HWE.vcf \
#-A HardyWeinberg

#perl ExtractHWE.pl Sparklef.keep.50.3.30.bi.75.filtered.aiken.HWE.vcf Sparklef.keep.50.3.30.bi.75.filtered.aiken.HWE.pass.txt

#HWE in jp
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --keep blue.jp.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.jp

#GenomeAnalysisTK \
#-R MendaxGenome/MendaxGenome.fasta \
#-T VariantAnnotator \
#--variant Sparklef.keep.50.3.30.bi.75.filtered.jp.recode.vcf \
#-o Sparklef.keep.50.3.30.bi.75.filtered.jp.HWE.vcf \
#-A HardyWeinberg

#perl ExtractHWE.pl Sparklef.keep.50.3.30.bi.75.filtered.jp.HWE.vcf Sparklef.keep.50.3.30.bi.75.filtered.jp.HWE.pass.txt

#HWE in ns
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --keep blue.ns.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.ns

#GenomeAnalysisTK \
#-R ../../MendaxGenome.fasta \
#-T VariantAnnotator \
#--variant Sparklef.keep.50.3.30.bi.75.filtered.ns.recode.vcf \
#-o Sparklef.keep.50.3.30.bi.75.filtered.ns.HWE.vcf \
#-A HardyWeinberg

#perl ExtractHWE.pl Sparklef.keep.50.3.30.bi.75.filtered.ns.HWE.vcf Sparklef.keep.50.3.30.bi.75.filtered.ns.HWE.pass.txt

#Here is where you could do HWE for new pops >30 individuals
#HWE in deerberry AL
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --keep db.al.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.db.al

#GenomeAnalysisTK \
#-R MendaxGenome/MendaxGenome.fasta \
#-T VariantAnnotator \
#--variant Sparklef.keep.50.3.30.bi.75.filtered.db.al.recode.vcf \
#-o Sparklef.keep.50.3.30.bi.75.filtered.db.al.HWE.vcf \
#-A HardyWeinberg

#perl ExtractHWE.pl Sparklef.keep.50.3.30.bi.75.filtered.db.al.HWE.vcf Sparklef.keep.50.3.30.bi.75.filtered.db.al.HWE.pass.txt

#HWE in sparkleberry AL
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --keep sb.al.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.sb.al

#GenomeAnalysisTK \
#-R MendaxGenome/MendaxGenome.fasta \
#-T VariantAnnotator \
#--variant Sparklef.keep.50.3.30.bi.75.filtered.sb.al.recode.vcf \
#-o Sparklef.keep.50.3.30.bi.75.filtered.sb.al.HWE.vcf \
#-A HardyWeinberg

#perl ExtractHWE.pl Sparklef.keep.50.3.30.bi.75.filtered.sb.al.HWE.vcf Sparklef.keep.50.3.30.bi.75.filtered.sb.al.HWE.pass.txt

#HWE in sparkleberry AR
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --keep sb.ar.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.sb.ar

#GenomeAnalysisTK \
#-R MendaxGenome/MendaxGenome.fasta \
#-T VariantAnnotator \
#--variant Sparklef.keep.50.3.30.bi.75.filtered.sb.ar.recode.vcf \
#-o Sparklef.keep.50.3.30.bi.75.filtered.sb.ar.HWE.vcf \
#-A HardyWeinberg

#perl ExtractHWE.pl Sparklef.keep.50.3.30.bi.75.filtered.sb.ar.HWE.vcf Sparklef.keep.50.3.30.bi.75.filtered.sb.ar.HWE.pass.txt

#HWE in sparkleberry SC
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.vcf --keep sb.sc.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.sb.sc

#GenomeAnalysisTK \
#-R MendaxGenome/MendaxGenome.fasta \
#-T VariantAnnotator \
#--variant Sparklef.keep.50.3.30.bi.75.filtered.sb.sc.recode.vcf \
#-o Sparklef.keep.50.3.30.bi.75.filtered.sb.sc.HWE.vcf \
#-A HardyWeinberg

#perl ExtractHWE.pl Sparklef.keep.50.3.30.bi.75.filtered.sb.sc.HWE.vcf Sparklef.keep.50.3.30.bi.75.filtered.sb.sc.HWE.pass.txt

#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.fenn.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.db.al.HWE.pass.txt	fenn.dbal.txt
#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.fenn.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.sb.al.HWE.pass.txt	fenn.sbal.txt
#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.fenn.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.sb.ar.HWE.pass.txt	fenn.sbar.txt
#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.fenn.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.sb.sc.HWE.pass.txt	fenn.sbsc.txt
#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.db.al.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.sb.al.HWE.pass.txt	dbal.sbal.txt
#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.db.al.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.sb.ar.HWE.pass.txt	dbal.sbar.txt
#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.db.al.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.sb.sc.HWE.pass.txt	dbal.sbsc.txt
#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.sb.al.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.sb.ar.HWE.pass.txt	sbal.sbar.txt
#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.sb.al.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.sb.sc.HWE.pass.txt	sbal.sbsc.txt
#python sharedSNPs2.py Sparklef.keep.50.3.30.bi.75.filtered.sb.sc.HWE.pass.txt Sparklef.keep.50.3.30.bi.75.filtered.sb.ar.HWE.pass.txt	sbsc.sbar.txt

#python sharedSNPs3.py dbal.sbar.txt sbal.sbsc.txt newSites.txt
#python sharedSNPs3.py newSites.txt fenn.dbal.txt fenn.newSites.txt

#perl subsetSNPs.C.pl fenn.newSites.txt Sparklef.keep.50.3.30.bi.75.filtered.vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.vcf

#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE --depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE --site-depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE --site-mean-depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE --missing-site
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE --missing-indv

#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.vcf --max-meanDP 11 --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP11
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.vcf --max-meanDP 14 --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.vcf --max-meanDP 20 --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP20

#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP11 --depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP11 --site-depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP11 --site-mean-depth
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP11 --missing-site
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP11 --missing-indv

#vcftools --vcf Sparklef.final.vcf --out Sparklef.final --missing-indv
#vcftools --vcf Sparklef.final.vcf --out Sparklef.final --depth

#DirecEstAllelFreq.5.pl
#DirecEstAllelFreq.pl


#python OnePerContigVCF.py Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf Sparklef.final.vcf

#make a faststructure file, cut off = 1, for faststructure analysis
#java -Xmx1024m -Xms512M -jar /afs/crc.nd.edu/user/m/mdoellma/bin/PGDSpider_2.1.0.3/PGDSpider2-cli.jar \
#-inputfile Sparklef.final.vcf -inputformat VCF \
#-outputfile Rmendax.fast.1.str -outputformat STRUCTURE -spid Rmendax.1.spid
#python RemoveMissing.fast.py Rmendax.fast.1.str 95

#make structure file, cutoff = 1, for PCA
#java -Xmx1024m -Xms512M -jar /afs/crc.nd.edu/user/m/mdoellma/bin/PGDSpider_2.1.0.3/PGDSpider2-cli.jar \
#-inputfile Sparklef.final.vcf -inputformat VCF \
#-outputfile Rmendax.1.str  -outputformat STRUCTURE -spid Rmendax.1B.spid
#python RemoveMissing.py Rmendax.1.str 95

#module load R/3.2.5
#Rscript PCA.rscript

#cat Rmendax.fast.1.95.str | awk '{print $1"\t"$2}' | uniq | awk '{print $2}' | grep -v 'SNP' | sed 's/15/SB_SC/g' | sed 's/14/SB_AR/g' | sed 's/13/SB_AL/g' | sed 's/12/DB_SC/g' | sed 's/11/DB_AR/g' | sed 's/10/DB_AL/g' | sed 's/9/SB_FL/g' | sed 's/8/DB_FL/g' | sed 's/7/BL_NS/g' | sed 's/6/BL_NJ/g' | sed 's/5/SB_KY/g' | sed 's/4/BL_IN/g' | sed 's/3/BL_MI/g' | sed 's/2/SB_GA/g' | sed 's/1/DB_SC2/g' > pop
#cat pop | uniq > poporder

#module load bio/faststructure/1.0
#depth >=1
#structure -K 1 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str
#structure -K 2 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str
#structure -K 3 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str
#structure -K 4 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str
#structure -K 5 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str
#structure -K 6 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str
#structure -K 7 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str
#structure -K 8 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str
#structure -K 9 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str
#structure -K 10 --input=Rmendax.fast.1.95 --output=out.Rmendax.fast.1.95 --format=str

#chooseK --input=out.Rmendax.fast.1.95

#python distruct2.1.py -K 2 --input=out.Rmendax.fast.1.95 --output='Rmendax.1.95.K2.svg' \
#--popfile=pop --title='R. mendax K=2'
#python distruct2.1.py -K 3 --input=out.Rmendax.fast.1.95 --output='Rmendax.1.95.K3.svg' \
#--popfile=pop --title='R. mendax K=3'
#python distruct2.1.py -K 4 --input=out.Rmendax.fast.1.95 --output='Rmendax.1.95.K4.svg' \
#--popfile=pop --title='R. mendax K=4'
#python distruct2.1.py -K 5 --input=out.Rmendax.fast.1.95 --output='Rmendax.1.95.K5.svg' \
#--popfile=pop --title='R. mendax K=5'
#python distruct2.1.py -K 6 --input=out.Rmendax.fast.1.95 --output='Rmendax.1.95.K6.svg' \
#--popfile=pop --title='R. mendax K=6'
#python distruct2.1.py -K 7 --input=out.Rmendax.fast.1.95 --output='Rmendax.1.95.K7.svg' \
#--popfile=pop --title='R. mendax K=7'
#python distruct2.1.py -K 8 --input=out.Rmendax.fast.1.95 --output='Rmendax.1.95.K8.svg' \
#--popfile=pop --title='R. mendax K=8'
#python distruct2.1.py -K 9 --input=out.Rmendax.fast.1.95 --output='Rmendax.1.95.K9.svg' \
#--popfile=pop --title='R. mendax K=9'
#python distruct2.1.py -K 10 --input=out.Rmendax.fast.1.95 --output='Rmendax.1.95.K10.svg' \
#--popfile=pop --title='R. mendax K=10'

#grep -v 'V.NJ.033' Rmendax.fast.1.95.str > Rmendax.fast.1.95.NJ.str

#grep -v 'V.NJ.033' Rmendax.1.95.str > Rmendax.1.95.NJ.str
#module load R/3.2.5
#Rscript PCA.NJ.rscript

#cat Rmendax.fast.1.95.NJ.str | awk '{print $1"\t"$2}' | uniq | awk '{print $2}' | grep -v 'SNP' | sed 's/15/SB_SC/g' | sed 's/14/SB_AR/g' | sed 's/13/SB_AL/g' | sed 's/12/DB_SC/g' | sed 's/11/DB_AR/g' | sed 's/10/DB_AL/g' | sed 's/9/SB_FL/g' | sed 's/8/DB_FL/g' | sed 's/7/BL_NS/g' | sed 's/6/BL_NJ/g' | sed 's/5/SB_KY/g' | sed 's/4/BL_IN/g' | sed 's/3/BL_MI/g' | sed 's/2/SB_GA/g' | sed 's/1/DB_SC2/g' > pop
#cat pop | uniq > poporder

#module load bio/faststructure/1.0
#depth >=1
#structure -K 1 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str
#structure -K 2 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str
#structure -K 3 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str
#structure -K 4 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str
#structure -K 5 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str
#structure -K 6 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str
#structure -K 7 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str
#structure -K 8 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str
#structure -K 9 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str
#structure -K 10 --input=Rmendax.fast.1.95.NJ --output=out.Rmendax.fast.1.95.NJ --format=str

#chooseK --input=out.Rmendax.fast.1.95.NJ

#python distruct2.1.py -K 2 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K2.v1.svg' --popfile=pop --title='R. mendax K=2'
#python distruct2.1.py -K 2 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K2.v2.svg' --popfile=pop --title='R. mendax K=2'
#python distruct2.1.py -K 2 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K2.svg' --popfile=pop --title='R. mendax K=2'
#python distruct2.1.py -K 3 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K3.svg' --popfile=pop --title='R. mendax K=3'
#python distruct2.1.py -K 4 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K4.svg' --popfile=pop --title='R. mendax K=4'
#python distruct2.1.py -K 5 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K5.svg' --popfile=pop --title='R. mendax K=5'
#python distruct2.1.py -K 6 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K6.svg' --popfile=pop --title='R. mendax K=6'
#python distruct2.1.py -K 7 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K7.svg' --popfile=pop --title='R. mendax K=7'
#python distruct2.1.py -K 8 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K8.svg' --popfile=pop --title='R. mendax K=8'
#python distruct2.1.py -K 9 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K9.svg' --popfile=pop --title='R. mendax K=9'
#python distruct2.1.py -K 10 --input=out.Rmendax.fast.1.95.NJ --output='Rmendax.1.95.NJ.K10.svg' --popfile=pop --title='R. mendax K=10'

#cat pop | sed -r 's/[[:alnum:]]*_//' | sed 's/Scotia/NS/' > temp
#mv temp pop
#cat pop | uniq > poporder

#module load perl

#perl arkansas.pl
#perl florida.pl
#perl alabama.pl
#perl southcarolina.pl

#perl MonteCarloSigRhagArkansas.pl arkansasdif.txt sigarkansasdif.txt textfiles/arkansas.txt
#perl MonteCarloSigRhag.pl floridadif.txt sigfloridadif.txt textfiles/florida.txt
#perl MonteCarloSigRhag.pl alabamadif.txt sigalabamadif.txt textfiles/alabama.txt
#perl MonteCarloSigRhag.pl southcarolinadif.txt sigsouthcarolinadif.txt textfiles/southcarolina.txt

#Structure run of blueberry and deerberry sites only
#cat Rmendax.fast.BBDBonly.str | awk '{print $1"\t"$2}' | uniq | awk '{print $2}' | grep -v 'SNP' | sed 's/15/SB_SC/g' | sed 's/14/SB_AR/g' | sed 's/13/SB_AL/g' | sed 's/12/DB_SC/g' | sed 's/11/DB_AR/g' | sed 's/10/DB_AL/g' | sed 's/9/SB_FL/g' | sed 's/8/DB_FL/g' | sed 's/7/BL_NS/g' | sed 's/6/BL_NJ/g' | sed 's/5/SB_KY/g' | sed 's/4/BL_IN/g' | sed 's/3/BL_MI/g' | sed 's/2/SB_GA/g' | sed 's/1/DB_SC2/g' > pop
#cat pop | uniq > poporder

#module load bio/faststructure/1.0
#depth >=1
#structure -K 1 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str
#structure -K 2 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str
#structure -K 3 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str
#structure -K 4 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str
#structure -K 5 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str
#structure -K 6 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str
#structure -K 7 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str
#structure -K 8 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str
#structure -K 9 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str
#structure -K 10 --input=Rmendax.fast.BBDBonly --output=out.Rmendax.fast.BBDBonly --format=str

#chooseK --input=out.Rmendax.fast.BBDBonly

#python distruct2.1.py -K 2 --input=out.Rmendax.fast.BBDBonly --output='Rmendax.BBDBonly.K2.svg' \
#--popfile=pop --title='R. mendax Deerberry and Blueberry K=2'
#python distruct2.1.py -K 3 --input=out.Rmendax.fast.BBDBonly --output='Rmendax.BBDBonly.K3.svg' \
#--popfile=pop --title='R. mendax Deerberry and Blueberry K=3'
#python distruct2.1.py -K 4 --input=out.Rmendax.fast.BBDBonly --output='Rmendax.BBDBonly.K4.svg' \
#--popfile=pop --title='R. mendax Deerberry and Blueberry K=4'
#python distruct2.1.py -K 5 --input=out.Rmendax.fast.BBDBonly --output='Rmendax.BBDBonly.K5.svg' \
#--popfile=pop --title='R. mendax Deerberry and Blueberry K=5'
#python distruct2.1.py -K 6 --input=out.Rmendax.fast.BBDBonly --output='Rmendax.BBDBonly.K6.svg' \
#--popfile=pop --title='R. mendax Deerberry and Blueberry K=6'
#python distruct2.1.py -K 7 --input=out.Rmendax.fast.BBDBonly --output='Rmendax.BBDBonly.K7.svg' \
#--popfile=pop --title='R. mendax Deerberry and Blueberry K=7'
#python distruct2.1.py -K 8 --input=out.Rmendax.fast.BBDBonly --output='Rmendax.BBDBonly.K8.svg' \
#--popfile=pop --title='R. mendax Deerberry and Blueberry K=8'
#python distruct2.1.py -K 9 --input=out.Rmendax.fast.BBDBonly --output='Rmendax.BBDBonly.K9.svg' \
#--popfile=pop --title='R. mendax Deerberry and Blueberry K=9'
#python distruct2.1.py -K 10 --input=out.Rmendax.fast.BBDBonly --output='Rmendax.BBDBonly.K10.svg' \
#--popfile=pop --title='R. mendax Deerberry and Blueberry K=10'

#Structure run of sparkleberry and deerberry sites only
#cat Rmendax.fast.SBDBonly.str | awk '{print $1"\t"$2}' | uniq | awk '{print $2}' | grep -v 'SNP' | sed 's/15/SB_SC/g' | sed 's/14/SB_AR/g' | sed 's/13/SB_AL/g' | sed 's/12/DB_SC/g' | sed 's/11/DB_AR/g' | sed 's/10/DB_AL/g' | sed 's/9/SB_FL/g' | sed 's/8/DB_FL/g' | sed 's/7/BL_NS/g' | sed 's/6/BL_NJ/g' | sed 's/5/SB_KY/g' | sed 's/4/BL_IN/g' | sed 's/3/BL_MI/g' | sed 's/2/SB_GA/g' | sed 's/1/DB_SC2/g' > pop
#cat pop | uniq > poporder

#module load bio/faststructure/1.0
#depth >=1
#structure -K 1 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str
#structure -K 2 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str
#structure -K 3 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str
#structure -K 4 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str
#structure -K 5 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str
#structure -K 6 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str
#structure -K 7 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str
#structure -K 8 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str
#structure -K 9 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str
#structure -K 10 --input=Rmendax.fast.SBDBonly --output=out.Rmendax.fast.SBDBonly --format=str

#chooseK --input=out.Rmendax.fast.SBDBonly

#python distruct2.1.py -K 2 --input=out.Rmendax.fast.SBDBonly --output='Rmendax.SBDBonly.K2.svg' \
#--popfile=pop --title='R. mendax Deerberry vs Sparkleberry K=2'
#python distruct2.1.py -K 3 --input=out.Rmendax.fast.SBDBonly --output='Rmendax.SBDBonly.K3.svg' \
#--popfile=pop --title='R. mendax Deerberry vs Sparkleberry K=3'
#python distruct2.1.py -K 4 --input=out.Rmendax.fast.SBDBonly --output='Rmendax.SBDBonly.K4.svg' \
#--popfile=pop --title='R. mendax Deerberry vs Sparkleberry K=4'
#python distruct2.1.py -K 5 --input=out.Rmendax.fast.SBDBonly --output='Rmendax.SBDBonly.K5.svg' \
#--popfile=pop --title='R. mendax Deerberry vs Sparkleberry K=5'
#python distruct2.1.py -K 6 --input=out.Rmendax.fast.SBDBonly --output='Rmendax.SBDBonly.K6.svg' \
#--popfile=pop --title='R. mendax Deerberry vs Sparkleberry K=6'
#python distruct2.1.py -K 7 --input=out.Rmendax.fast.SBDBonly --output='Rmendax.SBDBonly.K7.svg' \
#--popfile=pop --title='R. mendax Deerberry vs Sparkleberry K=7'
#python distruct2.1.py -K 8 --input=out.Rmendax.fast.SBDBonly --output='Rmendax.SBDBonly.K8.svg' \
#--popfile=pop --title='R. mendax Deerberry vs Sparkleberry K=8'
#python distruct2.1.py -K 9 --input=out.Rmendax.fast.SBDBonly --output='Rmendax.SBDBonly.K9.svg' \
#--popfile=pop --title='R. mendax Deerberry vs Sparkleberry K=9'
#python distruct2.1.py -K 10 --input=out.Rmendax.fast.SBDBonly --output='Rmendax.SBDBonly.K10.svg' \
#--popfile=pop --title='R. mendax Deerberry vs Sparkleberry K=10'

#module load R/3.2.5
#Rscript PCA.NJ.BBDB.rscript
#Rscript PCA.NJ.SBDB.rscript

#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode --het

#Trying something LD
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14 --geno-r2
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14 --interchrom-geno-r2

#DB pop FL
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --keep textfiles/odb.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.DB_FL
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.DB_FL.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.DB_FL --geno-r2
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.DB_FL.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.DB_FL --interchrom-geno-r2

#SB pop LF
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.recode.vcf --keep textfiles/osb.txt --recode --recode-INFO-all --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.SB_FL
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.SB_FL.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.SB_FL --geno-r2
#vcftools --vcf Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.SB_FL.recode.vcf --out Sparklef.keep.50.3.30.bi.75.filtered.HWE.DP14.SB_FL --interchrom-geno-r2

module load R/3.2.5
Rscript PCA.NJ.19.rscript
#Rscript PCA.NJ.19.119.120.rscript

