#!/bin/csh
#$ -M kinskeep@nd.edu
#$ -m abe
#$ -r y
#$ -pe smp 16
#$ -q long
#$ -N Preppin

module load bio

cd /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring

cp ../../../suavis/ftp.biotec.illinois.edu/Stephens_KAI_pool.201823.tgz .
echo Copied data file
tar -zxvf Stephens_KAI_pool.201823.tgz
#mv KAI_Pool_NoIndex_L005_R1_001.fastq Dogwoodf.fq
#mv KAI_Pool_NoIndex_L005_R2_001.fastq Dogwoodr.fq
#fastqc Dogwoodf.fq
#fastqc Dogwoodr.fq
#mv Dogwoodf_fastqc.* /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/Dogwoods/fastqc_results
#mv Dogwoodr_fastqc.* /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/Dogwoods/fastqc_results
#echo Fastqc has finished running >> Preppin_status.txt

#radtag0_trimmer.py -o Sparklef.demult.fq -p Sparkler.fq -x Sparkler.demult.fq -k -e 0 barcodes_DBSB.fixed.txt Sparklef.fq
#echo First Trimmer has finished running >> Preppin_status.txt
#mv Sparkle.info /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/trimmer


#trimmomatic PE -threads 16 -phred33 Sparklef.demult.fq Sparkler.demult.fq Sparklef.demult.decontam.fq Sparklef.demult.decontam.un.fq Sparkler.demult.decontam.fq Sparkler.demult.decontam.un.fq ILLUMINACLIP:TruSeq3-PE-2.fa:2:30:10

#radtag0_trimmer.py -o Sparklef.demult.decontam.trimmed.fq -p Sparkler.demult.decontam.fq -x Sparkler.demult.decontam.trimmed.fq -g -e 0 barcodes_DBSB.fixed.txt Sparklef.demult.decontam.fq
#radtag0_trimmer.py -o Sparklef.demult.decontam.un.trimmed.fq -g barcodes_DBSB.fixed.txt Sparklef.demult.decontam.un.fq
#echo Second Trimmer has finished running >> Preppin_status.txt
#mv Sparklef.demult.decontam.info /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/trimmer
#mv Sparklef.demult.decontam.un.info /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/trimmer

#trimmomatic PE -threads 16 -phred33 Sparklef.demult.decontam.trimmed.fq Sparkler.demult.decontam.trimmed.fq Sparklef.demult.decontam.trimmed.filt.fq Sparklef.demult.decontam.trimmed.filt.un.fq Sparkler.demult.decontam.trimmed.filt.fq Sparkler.demult.decontam.trimmed.filt.un.fq LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:30
#trimmomatic SE -threads 16 -phred33 Sparklef.demult.decontam.un.trimmed.fq Sparklef.demult.decontam.un.trimmed.filt.fq LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:30
#trimmomatic SE -threads 16 -phred33 Sparkler.demult.decontam.un.fq Sparkler.demult.decontam.un.filt.fq LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 HEADCROP:10 MINLEN:30

#python removeTTT.py Sparklef.demult.decontam.un.trimmed.filt.fq

#trimmomatic SE -threads 16 -phred33 Sparkler.demult.decontam.trimmed.filt.fq Sparkler.demult.decontam.trimmed.filt.crop.fq HEADCROP:10
#trimmomatic SE -threads 16 -phred33 Sparkler.demult.decontam.trimmed.filt.un.fq Sparkler.demult.decontam.trimmed.filt.un.crop.fq HEADCROP:10


#fastqc Sparklef.demult.decontam.trimmed.filt.fq
#fastqc Sparkler.demult.decontam.trimmed.filt.crop.fq
#mv Sparklef.demult.decontam.trimmed.filt_fastqc.* /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/fastqc_results
#mv Sparkler.demult.decontam.trimmed.filt.crop_fastqc.* /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/fastqc_results
#fastqc Sparklef.demult.decontam.trimmed.filt.un.fq
#fastqc Sparkler.demult.decontam.trimmed.filt.un.crop.fq
#mv Sparklef.demult.decontam.trimmed.filt.un_fastqc.* /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/fastqc_results
#mv Sparkler.demult.decontam.trimmed.filt.un.crop_fastqc.* /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/fastqc_results
#fastqc Sparklef.demult.decontam.un.trimmed.filt.noT.fq
#fastqc Sparkler.demult.decontam.un.filt.fq
#mv Sparklef.demult.decontam.un.trimmed.filt.noT_fastqc.* /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/fastqc_results
#mv Sparkler.demult.decontam.un.filt_fastqc.* /afs/crc.nd.edu/group/rhago/mendax/Katherine/2018_Spring/fastqc_results
#echo Fastqc has finished running >> Preppin_status.txt
